### ISSUE TITLE
Update to EntityFrameworkCore 1.1 kills the import export feature

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5Localization#20]
lifecycle problems  due to new EFCore 1.1
Reproduce - download, then update => exception
Just update => ok
Just download => ok

**Comment by damienbod** [comment]
{System.InvalidOperationException: The instance of entity type 'LocalizationRecord' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Localization.SqlLocalizer.DbStringLocalizer.SqlStringLocalizerFactory.UpdatetLocalizationData(List`1 data, String information) in C:\git\damienbod\AspNet5Localization\AspNet5Localization\src\Localization.SqlLocalizer\DbStringLocalizer\SqlStringLocalizerFactory.cs:line 135
   at ImportExportLocalization.Controllers.ImportExportController.ImportCsvFileForExistingData(CsvImportDescription csvImportDescription) in C:\git\damienbod\AspNet5Localization\AspNet5Localization\src\ImportExportLocalization\Controllers\ImportExportController.cs:line 51
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()}

**Comment by damienbod** [comment]
fixed
